version: '3.2'

services:
  postfix:
    build: .
    restart: always
    volumes:
      - /data/postfix/mail:/var/mail
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 465
        published: 465
        protocol: tcp
        mode: host
volumes:
    mail: