version: '3.2'

services:
  postfix:
    build: .
    restart: always
    volumes:
      - /data/postfix/etc:/etc/postfix
      - /data/postfix/ssl/ca.crt:/etc/ssl/certs/ca.crt
      - /data/postfix/ssl/server.crt:/etc/ssl/certs/server.crt
      - /data/postfix/ssl/server.key:/etc/ssl/certs/server.key
      - /data/postfix/log/mail.log:/var/log/maillog
      - /data/postfix/dovecot:/etc/dovecot
      - /data/mail:/root/Maildir
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
volumes:
    etc:
    dovecot:
    ca.crt:
    server.crt:
    server.key:
    mail.log:
    mail: